#!/bin/bash
#SBATCH --job-name=iter_dim_$1        # create a short name for your job
#SBATCH --nodes=1                # node count
#SBATCH --ntasks=1               # total number of tasks across all nodes
#SBATCH --cpus-per-task=1        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --mem-per-cpu=1G         # memory per cpu-core (4G per cpu-core is default)
#SBATCH --time=15:00:00          # total run time limit (HH:MM:SS)
#SBATCH --mail-type=fail          # send email when job begins, ends and fails
#SBATCH --mail-user=zidong@princeton.edu

module purge
module load anaconda3
conda activate tomtom-env

srun python -u iter_dim_3feat_parallel_spreadout.py $1
