#!/bin/bash
#SBATCH --job-name=mod-rec-test        # create a short name for your job
#SBATCH --nodes=1                # node count
#SBATCH --ntasks=1               # total number of tasks across all nodes
#SBATCH --cpus-per-task=10        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --mem-per-cpu=15G         # memory per cpu-core (4G per cpu-core is default)
#SBATCH --time=15:00:00          # total run time limit (HH:MM:SS)
#SBATCH --mail-type=all          # send email when job begins, ends and fails
#SBATCH --mail-user=zidong@princeton.edu

module purge
module load anaconda3
conda activate tomtom-env

srun python -u model_recovery_test_norm_all_grp_parallel.py
